{% set version = "13.8.1" %}
{% set min_python = ">=3.7.0" %}

package:
  name: rich-split
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/r/rich/rich-{{ version }}.tar.gz
    sha256: 9e9e8be20746eeb5372df4ccba60775e1d3ed819008760ad70291dd3273b0db3
  - folder: src
    url: https://github.com/Textualize/rich/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 693645e88bc475449756e9f1a193e2764b915a86a63be95a3f0b28ae15685551

build:
  noarch: python
  number: 0

requirements:
  host:
    - python {{ min_python }}
  run:
    - python {{ min_python }}

outputs:
  - name: rich
    build:
      noarch: python
      script:
        - cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - pip
        - poetry-core >=1.0.0
        - python {{ min_python }}
      run:
        # sync with normalized deps from poetry-generated setup.py
        - markdown-it-py >=2.2.0
        - pygments >=2.13.0,<3.0.0
        - python {{ min_python }}
        - typing_extensions >=4.0.0,<5.0.0
    test:
      imports:
        - rich
      commands:
        - pip check
      requires:
        - pip

  - name: rich-with-jupyter
    build:
      noarch: python
    requirements:
      host:
        - python {{ min_python }}
      run:
        - {{ pin_subpackage("rich", max_pin="x.x.x") }}
        - ipywidgets >=7.5.1,<9.0.0
        - python {{ min_python }}
    test:
      imports:
        - rich
      commands:
        - pip check
      requires:
        - pip

  - name: _rich-with-tests
    build:
      noarch: python
    requirements:
      host:
        - python {{ min_python }}
      run:
        - {{ pin_subpackage("rich", max_pin="x.x.x") }}
        - {{ pin_subpackage("rich-with-jupyter", max_pin="x.x.x") }}
        - python {{ min_python }}
    test:
      source_files:
        - src/tests
      imports:
        - rich
      commands:
        - pip check
        - pytest src/tests -vv --cov=rich --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=91
      requires:
        - attrs
        - pip
        - pytest >=7.0.0,<8.0.0
        - pytest-cov >=3.0.0,<4.0.0

about:
  home: https://github.com/Textualize/rich
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: Render rich text, tables, progress bars, syntax highlighting, markdown and more to the terminal

  description: |
    Rich is a Python library for rich text and beautiful formatting in the terminal.

    The Rich API makes it easy to add color and style to terminal output. Rich
    can also render pretty tables, progress bars, markdown, syntax highlighted
    source code, tracebacks, and more — out of the box.

  doc_url: https://rich.readthedocs.io
  dev_url: https://github.com/Textualize/rich

extra:
  feedstock-name: rich
  recipe-maintainers:
    - jan-janssen
    - willmcgugan
    - bollwyvl
