{% set min_python = ">=3.7.0" %}
{% set version = "13.3.4" %}
{% set min_python = ">=3.7.0" %}

package:
  name: rich-split
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/r/rich/rich-{{ version }}.tar.gz
    sha256: b5d573e13605423ec80bdd0cd5f8541f7844a0e71a13f74cf454ccb2f490708b
  - folder: src
    url: https://github.com/Textualize/rich/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 11f70b34b1e752557761e4a4ce0d15296db672a58ec8f0ae990cba73ce9a72cf

build:
  noarch: python
  number: 0

requirements:
  host:
    - python {{ min_python }}
  run:
    - python {{ min_python }}

outputs:
  - name: rich
    build:
      noarch: python
      script:
        - cd dist && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - pip
        - poetry-core >=1.0.0
        - python {{ min_python }}
      run:
        # sync with normalized deps from poetry-generated setup.py
        - markdown-it-py >=2.2.0,<3.0.0
        - pygments >=2.13.0,<3.0.0
        - python {{ min_python }}
        - typing_extensions >=4.0.0,<5.0.0
    test:
      imports:
        - rich
      commands:
        - pip check
      requires:
        - pip

  - name: rich-with-jupyter
    build:
      noarch: python
    requirements:
      host:
        - python {{ min_python }}
      run:
        - {{ pin_subpackage("rich", max_pin="x.x.x") }}
        - ipywidgets >=7.5.1,<9.0.0
        - python {{ min_python }}
    test:
      imports:
        - rich
      commands:
        - pip check
      requires:
        - pip

  - name: _rich-with-tests
    build:
      noarch: python
    requirements:
      host:
        - python {{ min_python }}
      run:
        - {{ pin_subpackage("rich", max_pin="x.x.x") }}
        - {{ pin_subpackage("rich-with-jupyter", max_pin="x.x.x") }}
        - python {{ min_python }}
    test:
      source_files:
        - src/tests
      imports:
        - rich
      commands:
        - pip check
        - pytest src/tests -vv --cov=rich --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=91
      requires:
        - attrs
        - pip
        - pytest >=7.0.0,<8.0.0
        - pytest-cov >=3.0.0,<4.0.0

about:
  home: https://github.com/Textualize/rich
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: Render rich text, tables, progress bars, syntax highlighting, markdown and more to the terminal

  description: |
    Rich is a Python library for rich text and beautiful formatting in the terminal.

    The Rich API makes it easy to add color and style to terminal output. Rich
    can also render pretty tables, progress bars, markdown, syntax highlighted
    source code, tracebacks, and more — out of the box.

  doc_url: https://rich.readthedocs.io
  dev_url: https://github.com/Textualize/rich

extra:
  feedstock-name: rich
  recipe-maintainers:
    - jan-janssen
    - willmcgugan
    - bollwyvl
